/**
 * Predictive Blocker Guard
 * Analyzes historical task patterns to predict and prevent future blockers
 */

// ============================================================================
// Types
// ============================================================================

export interface Task {
  id: string;
  title: string;
  status: 'pending' | 'in-progress' | 'completed' | 'blocked';
  dependencies?: string[];
  assignee?: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  estimatedHours?: number;
  actualHours?: number;
  createdAt: Date;
  completedAt?: Date;
  blockedAt?: Date;
  unblockedAt?: Date;
  blockReason?: string;
  tags?: string[];
  category?: string;
}

export interface BlockerPattern {
  id: string;
  name: string;
  description: string;
  conditions: PatternCondition[];
  frequency: number; // How often this pattern results in blockers (0-1)
  avgResolutionTime: number; // Average hours to resolve
  severity: 'low' | 'medium' | 'high' | 'critical';
  tags: string[];
  firstObserved: Date;
  lastObserved: Date;
  occurrenceCount: number;
}

export interface PatternCondition {
  type: 'dependency' | 'assignee' | 'priority' | 'estimate' | 'tag' | 'category' | 'timing';
  operator: 'equals' | 'contains' | 'gt' | 'lt' | 'exists' | 'missing';
  field?: string;
  value?: unknown;
  threshold?: number;
}

export interface PredictedBlocker {
  id: string;
  taskId: string;
  taskTitle: string;
  patternId: string;
  patternName: string;
  confidence: number; // 0-1
  severity: 'low' | 'medium' | 'high' | 'critical';
  predictedBlockTime: Date;
  reason: string;
  contributingFactors: string[];
  mitigationTasks: MitigationTask[];
  recommendedAction: string;
}

export interface MitigationTask {
  id: string;
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  estimatedHours: number;
  parentTaskId: string;
  blockerPatternId: string;
  autoGenerated: boolean;
  status: 'pending';
}

export interface PredictionOptions {
  minConfidence?: number;
  lookAheadDays?: number;
  autoMitigateThreshold?: number;
  maxPredictions?: number;
}

// ============================================================================
// PredictiveGuard Class
// ============================================================================

export class PredictiveGuard {
  private patterns: Map<string, BlockerPattern> = new Map();
  private predictions: Map<string, PredictedBlocker> = new Map();
  private historicalTasks: Task[] = [];
  private autoMitigateThreshold: number;

  constructor(options: { autoMitigateThreshold?: number } = {}) {
    this.autoMitigateThreshold = options.autoMitigateThreshold ?? 0.7;
  }

  /**
   * Load historical tasks for pattern analysis
   */
  loadHistoricalTasks(tasks: Task[]): void {
    this.historicalTasks = tasks.filter(t => t.createdAt);
  }

  /**
   * Analyze historical tasks to identify blocker patterns
   */
  analyzePatterns(historicalTasks: Task[]): BlockerPattern[] {
    this.loadHistoricalTasks(historicalTasks);
    
    const blockedTasks = historicalTasks.filter(t => t.status === 'blocked' || t.blockedAt);
    
    if (blockedTasks.length === 0) {
      return [];
    }

    const newPatterns: BlockerPattern[] = [];

    // Pattern 1: High priority tasks without clear dependencies
    const highPriorityNoDeps = this.detectHighPriorityNoDependenciesPattern(blockedTasks);
    if (highPriorityNoDeps) newPatterns.push(highPriorityNoDeps);

    // Pattern 2: Tasks with long estimated hours and no assignee
    const unassignedLargeTasks = this.detectUnassignedLargeTasksPattern(blockedTasks);
    if (unassignedLargeTasks) newPatterns.push(unassignedLargeTasks);

    // Pattern 3: Tasks blocked by external dependencies
    const externalDependencyBlocks = this.detectExternalDependencyPattern(blockedTasks);
    if (externalDependencyBlocks) newPatterns.push(externalDependencyBlocks);

    // Pattern 4: Tasks with underestimated hours
    const underestimationPattern = this.detectUnderestimationPattern(blockedTasks);
    if (underestimationPattern) newPatterns.push(underestimationPattern);

    // Pattern 5: Weekend/holiday boundary tasks
    const timingPattern = this.detectTimingPattern(blockedTasks);
    if (timingPattern) newPatterns.push(timingPattern);

    // Pattern 6: Specific assignee overload patterns
    const assigneeOverloadPattern = this.detectAssigneeOverloadPattern(blockedTasks);
    if (assigneeOverloadPattern) newPatterns.push(assigneeOverloadPattern);

    // Store discovered patterns
    for (const pattern of newPatterns) {
      this.patterns.set(pattern.id, pattern);
    }

    return [...this.patterns.values()];
  }

  /**
   * Predict potential blockers for current tasks
   */
  predictBlockers(
    currentTasks: Task[],
    options: PredictionOptions = {}
  ): PredictedBlocker[] {
    const {
      minConfidence = 0.3,
      lookAheadDays = 7,
      autoMitigateThreshold = this.autoMitigateThreshold,
      maxPredictions = 50
    } = options;

    const predictions: PredictedBlocker[] = [];
    const now = new Date();
    const lookAhead = new Date(now.getTime() + lookAheadDays * 24 * 60 * 60 * 1000);

    // Ensure we have patterns to match against
    if (this.patterns.size === 0) {
      // Try to analyze patterns from historical data first
      if (this.historicalTasks.length > 0) {
        this.analyzePatterns(this.historicalTasks);
      }
    }

    for (const task of currentTasks) {
      // Skip completed tasks
      if (task.status === 'completed') continue;

      for (const pattern of this.patterns.values()) {
        const matchScore = this.calculatePatternMatch(task, pattern);
        
        if (matchScore >= minConfidence) {
          const prediction = this.createPrediction(task, pattern, matchScore, lookAhead);
          
          // Auto-generate mitigation tasks if confidence is high enough
          if (matchScore >= autoMitigateThreshold) {
            prediction.mitigationTasks = this.generateMitigationTasks(task, pattern);
          }

          predictions.push(prediction);
          this.predictions.set(prediction.id, prediction);
        }
      }
    }

    // Sort by confidence (highest first) and limit
    predictions.sort((a, b) => b.confidence - a.confidence);
    
    return predictions.slice(0, maxPredictions);
  }

  /**
   * Get all identified patterns
   */
  getPatterns(): BlockerPattern[] {
    return [...this.patterns.values()];
  }

  /**
   * Get all active predictions
   */
  getPredictions(): PredictedBlocker[] {
    return [...this.predictions.values()];
  }

  /**
   * Clear all predictions (but keep patterns)
   */
  clearPredictions(): void {
    this.predictions.clear();
  }

  /**
   * Update confidence threshold for auto-mitigation
   */
  setAutoMitigateThreshold(threshold: number): void {
    this.autoMitigateThreshold = Math.max(0, Math.min(1, threshold));
  }

  // ============================================================================
  // Private: Pattern Detection
  // ============================================================================

  private detectHighPriorityNoDependenciesPattern(blockedTasks: Task[]): BlockerPattern | null {
    const matching = blockedTasks.filter(t => 
      t.priority === 'critical' && 
      (!t.dependencies || t.dependencies.length === 0) &&
      t.blockReason?.toLowerCase().includes('unclear')
    );

    const frequency = matching.length / blockedTasks.length;
    
    if (frequency < 0.1) return null;

    return {
      id: 'pattern-high-priority-no-deps',
      name: 'High Priority Without Dependencies',
      description: 'Critical/high priority tasks without clear dependencies often get blocked due to unclear scope or requirements',
      conditions: [
        { type: 'priority', operator: 'equals', field: 'priority', value: 'critical' },
        { type: 'dependency', operator: 'missing', field: 'dependencies' }
      ],
      frequency,
      avgResolutionTime: this.calculateAvgResolutionTime(matching),
      severity: 'high',
      tags: ['planning', 'scope', 'requirements'],
      firstObserved: this.getEarliestDate(matching.map(t => t.blockedAt)),
      lastObserved: this.getLatestDate(matching.map(t => t.blockedAt)),
      occurrenceCount: matching.length
    };
  }

  private detectUnassignedLargeTasksPattern(blockedTasks: Task[]): BlockerPattern | null {
    const matching = blockedTasks.filter(t => 
      !t.assignee && 
      (t.estimatedHours ?? 0) > 8 &&
      t.status === 'blocked'
    );

    const frequency = matching.length / blockedTasks.length;
    
    if (frequency < 0.1) return null;

    return {
      id: 'pattern-unassigned-large',
      name: 'Unassigned Large Tasks',
      description: 'Tasks with high effort estimates that lack assigned owners tend to stall',
      conditions: [
        { type: 'assignee', operator: 'missing', field: 'assignee' },
        { type: 'estimate', operator: 'gt', field: 'estimatedHours', threshold: 8 }
      ],
      frequency,
      avgResolutionTime: this.calculateAvgResolutionTime(matching),
      severity: 'medium',
      tags: ['assignment', 'ownership', 'estimation'],
      firstObserved: this.getEarliestDate(matching.map(t => t.blockedAt)),
      lastObserved: this.getLatestDate(matching.map(t => t.blockedAt)),
      occurrenceCount: matching.length
    };
  }

  private detectExternalDependencyPattern(blockedTasks: Task[]): BlockerPattern | null {
    const matching = blockedTasks.filter(t => 
      t.blockReason?.toLowerCase().includes('external') ||
      t.blockReason?.toLowerCase().includes('third party') ||
      t.blockReason?.toLowerCase().includes('waiting') ||
      t.tags?.some(tag => tag.toLowerCase().includes('external'))
    );

    const frequency = matching.length / blockedTasks.length;
    
    if (frequency < 0.05) return null;

    return {
      id: 'pattern-external-dependency',
      name: 'External Dependency Block',
      description: 'Tasks depending on external parties or third-party responses frequently get blocked',
      conditions: [
        { type: 'tag', operator: 'contains', field: 'tags', value: 'external' },
        { type: 'dependency', operator: 'exists', field: 'dependencies' }
      ],
      frequency,
      avgResolutionTime: this.calculateAvgResolutionTime(matching),
      severity: 'high',
      tags: ['external', 'third-party', 'dependency'],
      firstObserved: this.getEarliestDate(matching.map(t => t.blockedAt)),
      lastObserved: this.getLatestDate(matching.map(t => t.blockedAt)),
      occurrenceCount: matching.length
    };
  }

  private detectUnderestimationPattern(blockedTasks: Task[]): BlockerPattern | null {
    const matching = blockedTasks.filter(t => 
      t.estimatedHours && 
      t.actualHours && 
      t.actualHours > t.estimatedHours * 2
    );

    const frequency = matching.length / blockedTasks.length;
    
    if (frequency < 0.1) return null;

    return {
      id: 'pattern-underestimation',
      name: 'Chronic Underestimation',
      description: 'Tasks where actual time significantly exceeds estimates indicate planning issues',
      conditions: [
        { type: 'estimate', operator: 'exists', field: 'estimatedHours' },
        { type: 'estimate', operator: 'gt', field: 'actualHours', threshold: 1 }
      ],
      frequency,
      avgResolutionTime: this.calculateAvgResolutionTime(matching),
      severity: 'medium',
      tags: ['estimation', 'planning', 'scope-creep'],
      firstObserved: this.getEarliestDate(matching.map(t => t.blockedAt)),
      lastObserved: this.getLatestDate(matching.map(t => t.blockedAt)),
      occurrenceCount: matching.length
    };
  }

  private detectTimingPattern(blockedTasks: Task[]): BlockerPattern | null {
    const matching = blockedTasks.filter(t => {
      if (!t.blockedAt) return false;
      const day = t.blockedAt.getDay();
      return day === 5 || day === 6; // Friday or Saturday
    });

    const frequency = matching.length / blockedTasks.length;
    
    if (frequency < 0.15) return null;

    return {
      id: 'pattern-weekend-boundary',
      name: 'Weekend/Boundary Timing',
      description: 'Tasks blocked near weekends or holidays have longer resolution times',
      conditions: [
        { type: 'timing', operator: 'equals', field: 'createdAt.day', value: 'friday' }
      ],
      frequency,
      avgResolutionTime: this.calculateAvgResolutionTime(matching) + 48, // Add weekend hours
      severity: 'low',
      tags: ['timing', 'weekend', 'holiday'],
      firstObserved: this.getEarliestDate(matching.map(t => t.blockedAt)),
      lastObserved: this.getLatestDate(matching.map(t => t.blockedAt)),
      occurrenceCount: matching.length
    };
  }

  private detectAssigneeOverloadPattern(blockedTasks: Task[]): BlockerPattern | null {
    const assigneeTaskCounts = new Map<string, number>();
    
    for (const task of this.historicalTasks) {
      if (task.assignee) {
        assigneeTaskCounts.set(task.assignee, (assigneeTaskCounts.get(task.assignee) || 0) + 1);
      }
    }

    const overloadedAssignees = [...assigneeTaskCounts.entries()]
      .filter(([, count]) => count > 5)
      .map(([assignee]) => assignee);

    const matching = blockedTasks.filter(t => 
      t.assignee && overloadedAssignees.includes(t.assignee)
    );

    const frequency = matching.length / blockedTasks.length;
    
    if (frequency < 0.1) return null;

    return {
      id: 'pattern-assignee-overload',
      name: 'Assignee Overload',
      description: 'Assignees with high task volumes are more likely to have blocked tasks',
      conditions: [
        { type: 'assignee', operator: 'exists', field: 'assignee' },
        { type: 'assignee', operator: 'equals', field: 'taskCount', threshold: 5 }
      ],
      frequency,
      avgResolutionTime: this.calculateAvgResolutionTime(matching),
      severity: 'medium',
      tags: ['workload', 'assignee', 'capacity'],
      firstObserved: this.getEarliestDate(matching.map(t => t.blockedAt)),
      lastObserved: this.getLatestDate(matching.map(t => t.blockedAt)),
      occurrenceCount: matching.length
    };
  }

  // ============================================================================
  // Private: Prediction Creation
  // ============================================================================

  private calculatePatternMatch(task: Task, pattern: BlockerPattern): number {
    let matchScore = 0;
    let conditionCount = pattern.conditions.length;

    for (const condition of pattern.conditions) {
      const matches = this.evaluateCondition(task, condition);
      if (matches) {
        matchScore += 1 / conditionCount;
      }
    }

    // Adjust by pattern frequency (learned from history)
    matchScore *= (0.5 + pattern.frequency * 0.5);

    // Boost score for high-severity patterns on critical tasks
    if (task.priority === 'critical' && pattern.severity === 'high') {
      matchScore = Math.min(1, matchScore * 1.2);
    }

    return Math.round(matchScore * 100) / 100;
  }

  private evaluateCondition(task: Task, condition: PatternCondition): boolean {
    const value = condition.field ? (task as Record<string, unknown>)[condition.field] : undefined;

    switch (condition.operator) {
      case 'equals':
        return value === condition.value;
      case 'contains':
        if (Array.isArray(value)) {
          return value.includes(condition.value);
        }
        if (typeof value === 'string') {
          return value.toLowerCase().includes(String(condition.value).toLowerCase());
        }
        return false;
      case 'gt':
        return typeof value === 'number' && value > (condition.threshold ?? 0);
      case 'lt':
        return typeof value === 'number' && value < (condition.threshold ?? 0);
      case 'exists':
        return value !== undefined && value !== null && 
          !(Array.isArray(value) && value.length === 0) &&
          !(typeof value === 'string' && value.trim() === '');
      case 'missing':
        return value === undefined || value === null || 
          (Array.isArray(value) && value.length === 0) ||
          (typeof value === 'string' && value.trim() === '');
      default:
        return false;
    }
  }

  private createPrediction(
    task: Task, 
    pattern: BlockerPattern, 
    confidence: number,
    lookAhead: Date
  ): PredictedBlocker {
    const now = new Date();
    const predictedBlockTime = new Date(now.getTime() + 
      (24 * 60 * 60 * 1000 * (1 + (1 - confidence) * 3)));

    const contributingFactors: string[] = [];
    
    for (const condition of pattern.conditions) {
      const matches = this.evaluateCondition(task, condition);
      if (matches) {
        contributingFactors.push(`${condition.type}: ${condition.field} ${condition.operator} ${condition.value ?? condition.threshold}`);
      }
    }

    return {
      id: `pred-${task.id}-${pattern.id}-${Date.now()}`,
      taskId: task.id,
      taskTitle: task.title,
      patternId: pattern.id,
      patternName: pattern.name,
      confidence,
      severity: pattern.severity,
      predictedBlockTime: predictedBlockTime > lookAhead ? lookAhead : predictedBlockTime,
      reason: pattern.description,
      contributingFactors,
      mitigationTasks: [], // Will be populated if confidence > threshold
      recommendedAction: this.getRecommendedAction(pattern, task)
    };
  }

  // ============================================================================
  // Private: Mitigation Generation
  // ============================================================================

  private generateMitigationTasks(task: Task, pattern: BlockerPattern): MitigationTask[] {
    const mitigations: MitigationTask[] = [];

    switch (pattern.id) {
      case 'pattern-high-priority-no-deps':
        mitigations.push({
          id: `mit-${task.id}-deps-1`,
          title: `Define dependencies for: ${task.title}`,
          description: 'Identify and document all task dependencies before starting work',
          priority: 'high',
          estimatedHours: 1,
          parentTaskId: task.id,
          blockerPatternId: pattern.id,
          autoGenerated: true,
          status: 'pending'
        });
        break;

      case 'pattern-unassigned-large':
        mitigations.push({
          id: `mit-${task.id}-assign-1`,
          title: `Assign owner to: ${task.title}`,
          description: 'Assign a clear owner to prevent task from stalling',
          priority: 'high',
          estimatedHours: 0.5,
          parentTaskId: task.id,
          blockerPatternId: pattern.id,
          autoGenerated: true,
          status: 'pending'
        }, {
          id: `mit-${task.id}-estimate-1`,
          title: `Break down: ${task.title}`,
          description: 'Break task into smaller subtasks for better tracking',
          priority: 'medium',
          estimatedHours: 1,
          parentTaskId: task.id,
          blockerPatternId: pattern.id,
          autoGenerated: true,
          status: 'pending'
        });
        break;

      case 'pattern-external-dependency':
        mitigations.push({
          id: `mit-${task.id}-external-1`,
          title: `Set up external dependency tracking for: ${task.title}`,
          description: 'Establish clear communication channel and follow-up schedule with external party',
          priority: 'high',
          estimatedHours: 0.5,
          parentTaskId: task.id,
          blockerPatternId: pattern.id,
          autoGenerated: true,
          status: 'pending'
        });
        break;

      case 'pattern-underestimation':
        mitigations.push({
          id: `mit-${task.id}-review-1`,
          title: `Re-estimate: ${task.title}`,
          description: 'Review and update time estimate with team input',
          priority: 'medium',
          estimatedHours: 0.5,
          parentTaskId: task.id,
          blockerPatternId: pattern.id,
          autoGenerated: true,
          status: 'pending'
        });
        break;

      case 'pattern-assignee-overload':
        mitigations.push({
          id: `mit-${task.id}-redistribute-1`,
          title: `Review workload for ${task.assignee}`,
          description: 'Redistribute tasks or adjust priorities to prevent overload',
          priority: 'urgent',
          estimatedHours: 1,
          parentTaskId: task.id,
          blockerPatternId: pattern.id,
          autoGenerated: true,
          status: 'pending'
        });
        break;
    }

    // Add a generic tracking mitigation if no specific ones generated
    if (mitigations.length === 0) {
      mitigations.push({
        id: `mit-${task.id}-monitor-1`,
        title: `Monitor: ${task.title} for blockers`,
        description: `Watch for ${pattern.name} pattern indicators`,
        priority: 'medium',
        estimatedHours: 0.25,
        parentTaskId: task.id,
        blockerPatternId: pattern.id,
        autoGenerated: true,
        status: 'pending'
      });
    }

    return mitigations;
  }

  private getRecommendedAction(pattern: BlockerPattern, task: Task): string {
    const actions: Record<string, string> = {
      'pattern-high-priority-no-deps': 'Define clear dependencies and acceptance criteria before starting',
      'pattern-unassigned-large': 'Assign an owner and consider breaking into smaller tasks',
      'pattern-external-dependency': 'Set up proactive communication schedule with external parties',
      'pattern-underestimation': 'Re-estimate with buffer time and team review',
      'pattern-weekend-boundary': 'Plan handoff documentation for weekend coverage',
      'pattern-assignee-overload': 'Redistribute work or reprioritize to balance workload'
    };

    return actions[pattern.id] || 'Monitor closely and address early warning signs';
  }

  // ============================================================================
  // Private: Utilities
  // ============================================================================

  private calculateAvgResolutionTime(tasks: Task[]): number {
    const resolvedTasks = tasks.filter(t => t.unblockedAt && t.blockedAt);
    
    if (resolvedTasks.length === 0) return 0;

    const totalHours = resolvedTasks.reduce((sum, t) => {
      const blocked = t.blockedAt!.getTime();
      const unblocked = t.unblockedAt!.getTime();
      return sum + (unblocked - blocked) / (1000 * 60 * 60);
    }, 0);

    return Math.round(totalHours / resolvedTasks.length);
  }

  private getEarliestDate(dates: (Date | undefined)[]): Date {
    const validDates = dates.filter((d): d is Date => d instanceof Date);
    if (validDates.length === 0) return new Date();
    return new Date(Math.min(...validDates.map(d => d.getTime())));
  }

  private getLatestDate(dates: (Date | undefined)[]): Date {
    const validDates = dates.filter((d): d is Date => d instanceof Date);
    if (validDates.length === 0) return new Date();
    return new Date(Math.max(...validDates.map(d => d.getTime())));
  }
}

// ============================================================================
// Export factory function
// ============================================================================

export function createPredictiveGuard(options?: { autoMitigateThreshold?: number }): PredictiveGuard {
  return new PredictiveGuard(options);
}

export default PredictiveGuard;
