/**
 * Autonomous Task Generator
 * 
 * Transforms recommendations and system signals into actionable autonomous tasks.
 * Part of Phase 4A - Autonomous Decision Making Subsystem.
 * 
 * Creates tasks from:
 * - KPI anomalies detected by the recommendation engine
 * - Blocked work that needs unblocking
 * - Strategic gaps identified in planning
 */

import type { Recommendation, RecommendationPriority } from '@/lib/intelligence/recommendation-engine';
import type { KpiTrend } from '@/lib/predictions/simple-forecast';

// ==========================================
// Type Definitions
// ==========================================

export type TaskPriority = 'critical' | 'high' | 'medium' | 'low';

export type TaskStatus = 
  | 'pending'
  | 'assigned'
  | 'in_progress'
  | 'blocked'
  | 'completed'
  | 'cancelled';

export type TaskType =
  | 'investigation'
  | 'unblock'
  | 'strategy'
  | 'remediation'
  | 'optimization';

export interface AutonomousTask {
  id: string;
  type: TaskType;
  title: string;
  description: string;
  priority: TaskPriority;
  status: TaskStatus;
  
  // Source tracking
  sourceRecommendationId?: string;
  sourceType: 'kpi_anomaly' | 'blocked_work' | 'strategic_gap' | 'manual';
  
  // Context links
  relatedMetrics: string[];
  relatedObjectives: string[];
  blockedTaskIds?: string[];
  
  // Assignment
  assignedTo?: string;
  suggestedAssignees: string[];
  
  // Timeline
  createdAt: string;
  dueDate?: string;
  estimatedDuration: number; // in minutes
  
  // Resolution
  resolution?: {
    type: 'fixed' | 'mitigated' | 'no_action_needed' | 'transferred';
    summary: string;
    completedAt: string;
  };
  
  // Metadata
  tags: string[];
  autoGenerated: boolean;
  confidenceScore: number;
}

// Input types for task generation methods
export interface KPIAnomalyInput {
  metric: string;
  trend: KpiTrend;
  severity: 'critical' | 'warning' | 'notice';
  deviationPercent: number;
  expectedRange: { min: number; max: number };
  relatedMetrics?: string[];
}

export interface BlockedWorkInput {
  taskId: string;
  taskTitle: string;
  blockedReason: string;
  blockedSince: string;
  blockerType: 'dependency' | 'resource' | 'approval' | 'information' | 'technical';
  dependencies?: string[];
  owner?: string;
  impactScore: number; // 0-100
}

export interface StrategicGapInput {
  objectiveId: string;
  objectiveTitle: string;
  gapType: 'coverage' | 'capacity' | 'capability' | 'coordination';
  description: string;
  affectedTeams?: string[];
  estimatedImpact: string;
  timeline: 'immediate' | 'short_term' | 'long_term';
  relatedRecommendations?: string[];
}

// ==========================================
// Autonomous Task Generator
// ==========================================

export class AutonomousTaskGenerator {
  private config: {
    defaultDueDateHours: number;
    autoAssignThreshold: number;
    highPriorityThreshold: number;
  };

  constructor(config?: Partial<AutonomousTaskGenerator['config']>) {
    this.config = {
      defaultDueDateHours: 48,
      autoAssignThreshold: 0.8,
      highPriorityThreshold: 75,
      ...config,
    };
  }

  /**
   * Generate an investigation task from a detected KPI anomaly.
   * Creates a task to investigate why a metric deviated from expected behavior.
   */
  generateFromKPIAnomaly(anomaly: KPIAnomalyInput): AutonomousTask {
    const id = this.generateTaskId('investigation');
    const priority = this.mapSeverityToPriority(anomaly.severity);
    const dueDate = this.calculateDueDate(priority);
    const estimatedDuration = this.calculateInvestigationDuration(anomaly);
    
    const deviationDirection = anomaly.deviationPercent > 0 ? 'above' : 'below';
    const deviationMagnitude = Math.abs(anomaly.deviationPercent).toFixed(1);

    return {
      id,
      type: 'investigation',
      title: `Investigate ${anomaly.metric} anomaly (${deviationDirection} ${deviationMagnitude}%)`,
      description: this.buildKPIDescription(anomaly),
      priority,
      status: 'pending',
      sourceType: 'kpi_anomaly',
      relatedMetrics: [anomaly.metric, ...(anomaly.relatedMetrics || [])],
      relatedObjectives: [],
      suggestedAssignees: this.suggestInvestigationAssignees(anomaly),
      createdAt: new Date().toISOString(),
      dueDate,
      estimatedDuration,
      tags: ['auto-generated', 'kpi-anomaly', anomaly.severity, `metric:${anomaly.metric}`],
      autoGenerated: true,
      confidenceScore: this.calculateAnomalyConfidence(anomaly),
    };
  }

  /**
   * Generate an unblock task from a blocked work item.
   * Creates a task to resolve blockers and restore workflow velocity.
   */
  generateFromBlockedWork(blockedTask: BlockedWorkInput): AutonomousTask {
    const id = this.generateTaskId('unblock');
    const priority = this.calculateBlockedTaskPriority(blockedTask);
    const dueDate = this.calculateBlockedTaskDueDate(blockedTask);
    
    return {
      id,
      type: 'unblock',
      title: `Unblock: ${blockedTask.taskTitle}`,
      description: this.buildBlockedWorkDescription(blockedTask),
      priority,
      status: 'pending',
      sourceType: 'blocked_work',
      blockedTaskIds: [blockedTask.taskId, ...(blockedTask.dependencies || [])],
      relatedMetrics: [],
      relatedObjectives: [],
      suggestedAssignees: blockedTask.owner ? [blockedTask.owner] : [],
      createdAt: new Date().toISOString(),
      dueDate,
      estimatedDuration: this.calculateUnblockDuration(blockedTask),
      tags: [
        'auto-generated',
        'blocked-work',
        `blocker:${blockedTask.blockerType}`,
        `impact:${blockedTask.impactScore > 75 ? 'high' : blockedTask.impactScore > 50 ? 'medium' : 'low'}`,
      ],
      autoGenerated: true,
      confidenceScore: this.calculateBlockedWorkConfidence(blockedTask),
    };
  }

  /**
   * Generate a strategy task from an identified strategic gap.
   * Creates a task to address gaps in objectives coverage or capabilities.
   */
  generateFromStrategicGap(gap: StrategicGapInput): AutonomousTask {
    const id = this.generateTaskId('strategy');
    const priority = this.mapTimelineToPriority(gap.timeline);
    const dueDate = this.calculateGapDueDate(gap);
    
    return {
      id,
      type: 'strategy',
      title: `Address gap: ${gap.objectiveTitle}`,
      description: this.buildStrategicGapDescription(gap),
      priority,
      status: 'pending',
      sourceType: 'strategic_gap',
      relatedMetrics: [],
      relatedObjectives: [gap.objectiveId],
      suggestedAssignees: this.suggestStrategyAssignees(gap),
      createdAt: new Date().toISOString(),
      dueDate,
      estimatedDuration: this.calculateStrategyDuration(gap),
      tags: [
        'auto-generated',
        'strategic-gap',
        `type:${gap.gapType}`,
        `timeline:${gap.timeline}`,
        ...(gap.affectedTeams || []).map(t => `team:${t}`),
      ],
      autoGenerated: true,
      confidenceScore: this.calculateGapConfidence(gap),
    };
  }

  // ==========================================
  // Helper Methods
  // ==========================================

  private generateTaskId(type: TaskType): string {
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(2, 9);
    return `task_${type}_${timestamp}_${random}`;
  }

  private mapSeverityToPriority(severity: KPIAnomalyInput['severity']): TaskPriority {
    const mapping: Record<KPIAnomalyInput['severity'], TaskPriority> = {
      critical: 'critical',
      warning: 'high',
      notice: 'medium',
    };
    return mapping[severity];
  }

  private mapTimelineToPriority(timeline: StrategicGapInput['timeline']): TaskPriority {
    const mapping: Record<StrategicGapInput['timeline'], TaskPriority> = {
      immediate: 'critical',
      short_term: 'high',
      long_term: 'medium',
    };
    return mapping[timeline];
  }

  private mapRecPriorityToTaskPriority(priority: RecommendationPriority): TaskPriority {
    const mapping: Record<RecommendationPriority, TaskPriority> = {
      critical: 'critical',
      high: 'high',
      medium: 'medium',
      low: 'low',
    };
    return mapping[priority];
  }

  private calculateDueDate(priority: TaskPriority): string {
    const hours = {
      critical: 4,
      high: 24,
      medium: 72,
      low: this.config.defaultDueDateHours,
    }[priority];

    return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
  }

  private calculateBlockedTaskDueDate(blockedTask: BlockedWorkInput): string {
    // Calculate urgency based on how long it's been blocked and impact
    const blockedDuration = Date.now() - new Date(blockedTask.blockedSince).getTime();
    const blockedHours = blockedDuration / (1000 * 60 * 60);
    
    if (blockedTask.impactScore > 80 || blockedHours > 48) {
      return new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(); // 4 hours
    } else if (blockedTask.impactScore > 50 || blockedHours > 24) {
      return new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(); // 24 hours
    }
    return new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(); // 48 hours
  }

  private calculateGapDueDate(gap: StrategicGapInput): string {
    const days = {
      immediate: 1,
      short_term: 7,
      long_term: 30,
    }[gap.timeline];

    return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
  }

  private buildKPIDescription(anomaly: KPIAnomalyInput): string {
    const deviationDirection = anomaly.deviationPercent > 0 ? 'above' : 'below';
    const expectedRange = `${anomaly.expectedRange.min.toFixed(1)}-${anomaly.expectedRange.max.toFixed(1)}`;
    
    return `Metric "${anomaly.metric}" has deviated ${deviationDirection} expected range (${expectedRange}). ` +
           `Current trend: ${anomaly.trend.direction} ${Math.abs(anomaly.trend.changePercent).toFixed(1)}% ` +
           `(${anomaly.severity} severity).\n\n` +
           `Investigation needed to determine root cause and appropriate remediation.`;
  }

  private buildBlockedWorkDescription(blockedTask: BlockedWorkInput): string {
    const blockedSince = new Date(blockedTask.blockedSince).toLocaleDateString();
    
    let description = `Task "${blockedTask.taskTitle}" has been blocked since ${blockedSince}.\n\n`;
    description += `Blocker Type: ${blockedTask.blockerType}\n`;
    description += `Reason: ${blockedTask.blockedReason}\n`;
    description += `Impact Score: ${blockedTask.impactScore}/100\n\n`;
    
    if (blockedTask.dependencies && blockedTask.dependencies.length > 0) {
      description += `Dependencies: ${blockedTask.dependencies.join(', ')}\n`;
    }
    
    description += '\nAction required to unblock and restore workflow momentum.';
    
    return description;
  }

  private buildStrategicGapDescription(gap: StrategicGapInput): string {
    let description = `Strategic gap identified in objective "${gap.objectiveTitle}":\n\n`;
    description += `Gap Type: ${gap.gapType}\n`;
    description += `Description: ${gap.description}\n`;
    description += `Timeline: ${gap.timeline}\n`;
    description += `Estimated Impact: ${gap.estimatedImpact}\n`;
    
    if (gap.affectedTeams && gap.affectedTeams.length > 0) {
      description += `\nAffected Teams: ${gap.affectedTeams.join(', ')}`;
    }
    
    return description;
  }

  private calculateInvestigationDuration(anomaly: KPIAnomalyInput): number {
    // Base duration in minutes
    const baseDuration = 60;
    
    // Severity multipliers
    const severityMultipliers = {
      critical: 2.5,
      warning: 1.5,
      notice: 1.0,
    };
    
    return Math.round(baseDuration * severityMultipliers[anomaly.severity]);
  }

  private calculateUnblockDuration(blockedTask: BlockedWorkInput): number {
    // Base duration depends on blocker type
    const baseDurations = {
      dependency: 30,
      resource: 120,
      approval: 60,
      information: 45,
      technical: 240,
    };
    
    const base = baseDurations[blockedTask.blockerType];
    const impactMultiplier = blockedTask.impactScore > 75 ? 1.5 : 1.0;
    
    return Math.round(base * impactMultiplier);
  }

  private calculateStrategyDuration(gap: StrategicGapInput): number {
    const baseDurations = {
      immediate: 480,   // 8 hours
      short_term: 120,  // 2 hours
      long_term: 60,    // 1 hour
    };
    
    return baseDurations[gap.timeline];
  }

  private suggestInvestigationAssignees(anomaly: KPIAnomalyInput): string[] {
    // In a real implementation, this would query a user-skill matrix
    // For now, return empty to allow manual assignment
    return [];
  }

  private suggestStrategyAssignees(gap: StrategicGapInput): string[] {
    // In a real implementation, this would use objective ownership data
    return [];
  }

  private calculateBlockedTaskPriority(blockedTask: BlockedWorkInput): TaskPriority {
    if (blockedTask.impactScore >= 80) return 'critical';
    if (blockedTask.impactScore >= 60) return 'high';
    if (blockedTask.impactScore >= 40) return 'medium';
    return 'low';
  }

  private calculateAnomalyConfidence(anomaly: KPIAnomalyInput): number {
    // Confidence based on severity and deviation magnitude
    const severityScores = { critical: 95, warning: 80, notice: 65 };
    const baseScore = severityScores[anomaly.severity];
    const deviationFactor = Math.min(Math.abs(anomaly.deviationPercent) / 10, 1);
    
    return Math.min(100, Math.round(baseScore + deviationFactor * 5));
  }

  private calculateBlockedWorkConfidence(blockedTask: BlockedWorkInput): number {
    // Confidence based on impact score and blocker clarity
    const baseScore = blockedTask.impactScore;
    const hasClearReason = blockedTask.blockedReason.length > 10 ? 5 : 0;
    
    return Math.min(100, baseScore + hasClearReason);
  }

  private calculateGapConfidence(gap: StrategicGapInput): number {
    // Confidence based on clarity of gap description and timeline
    const baseScore = gap.description.length > 50 ? 70 : 50;
    const hasTeams = gap.affectedTeams && gap.affectedTeams.length > 0 ? 10 : 0;
    const hasImpact = gap.estimatedImpact.length > 20 ? 10 : 0;
    
    return Math.min(100, baseScore + hasTeams + hasImpact);
  }
}

// ==========================================
// Utility Functions
// ==========================================

/**
 * Create a task generator from a recommendation
 */
export function createTaskFromRecommendation(
  recommendation: Recommendation,
  generator?: AutonomousTaskGenerator
): AutonomousTask {
  const gen = generator || new AutonomousTaskGenerator();
  
  // Determine the appropriate input type based on recommendation type
  if (recommendation.type === 'investigate_decline' || recommendation.type === 'address_anomaly') {
    const trend = recommendation.sourceTrends[0];
    if (trend) {
      return gen.generateFromKPIAnomaly({
        metric: recommendation.sourceMetrics[0] || 'unknown',
        trend,
        severity: recommendation.priority === 'critical' ? 'critical' : 'warning',
        deviationPercent: trend.changePercent,
        expectedRange: { min: trend.avg7dValue * 0.9, max: trend.avg7dValue * 1.1 },
      });
    }
  }
  
  if (recommendation.type === 'review_blocked_tasks') {
    return gen.generateFromBlockedWork({
      taskId: `blocked_${Date.now()}`,
      taskTitle: recommendation.title,
      blockedReason: recommendation.description,
      blockedSince: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      blockerType: 'dependency',
      impactScore: recommendation.confidenceScore,
    });
  }
  
  // Default: treat as strategic gap
  return gen.generateFromStrategicGap({
    objectiveId: `obj_${Date.now()}`,
    objectiveTitle: recommendation.title,
    gapType: 'coverage',
    description: recommendation.description,
    timeline: recommendation.priority === 'critical' ? 'immediate' : 'short_term',
    estimatedImpact: recommendation.suggestedAction.estimatedImpact,
  });
}

/**
 * Batch process a list of recommendations into tasks
 */
export function batchGenerateTasks(
  recommendations: Recommendation[],
  generator?: AutonomousTaskGenerator
): AutonomousTask[] {
  const gen = generator || new AutonomousTaskGenerator();
  
  return recommendations
    .filter(r => r.confidenceScore >= 50) // Only generate tasks for confident recommendations
    .map(r => createTaskFromRecommendation(r, gen));
}

// Default export
export default AutonomousTaskGenerator;